/*
 *  Project SIPx
 *  -------------
 *  SIPx is a flexible and extensible SIP engine designed primarily for
 *  troubleshooting, edge-case testing, and IMS-related scenarios. It provides
 *  developers and DevOps engineers fine-grained control over SIP behavior,
 *  including non-RFC-compliant flows and corner-case simulations.
 *
 *  Description of Event:
 *  ---------------------
 *  Event is the fundamental data structure used for communication between
 *  SIPx modules. Each Event represents a specific action or state change inside
 *  the engine (e.g. receiving raw packets, parsed SIP messages, media events,
 *  or internal control triggers).
 *
 *  Main responsibilities:
 *    • Encapsulate event metadata through the EventType enum
 *    • Transport optional data such as raw message payloads, parsed SIP messages
 *      or log strings
 *    • Indicate ownership transfer when modules need to take over memory
 *
 *  Internal structure:
 *    • EventType 'type' describing the category of the event
 *    • Optional data fields:
 *        - log_message: string_view for lightweight logging events
 *        - raw_msg: pointer to raw SIP/UDP payload (heap-managed externally)
 *        - parsed_msg: pointer to SIPMessage instances created by the parser
 *    • ownership_claimed: used to mark that a receiving module has taken over
 *      responsibility for raw_msg or parsed_msg
 *
 *  Purpose and usage:
 *    Events are generated by various SIPx modules (network receiver, parser,
 *    logwriter, call logic, etc.) and distributed through the EventDispatcher.
 *    Handlers can react to the event, inspect attached SIP state, or claim
 *    ownership of message objects when needed.
 *
 *  Author:  Dennis Kühnlein
 *  Version: v0.1
 *  Created: 08.12.2025
 *
 *  License:
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 */


#ifndef PROJECT_SIPX_EVENT_H
#define PROJECT_SIPX_EVENT_H
#include <cstdint>
#include <string>
#include <string_view>
#include "../app/SIPxApp.h"


class SIPMessage;

enum class EventType {
    CREATE_NETWORK_SOCKET,
    NETWORK_SOCKET_CREATED,
    NETWORK_FAILED,
    NETWORK_SOCKET_CLOSED,
    RAW_MESSAGE_RECEIVED,
    MESSAGE_PARSED,
    SEND_MESSAGE,
    TIME_TO_REGISTER,
    INITIATE_CALL,
    START_MEDIA,
    SEND_MEDIA,
    RECEIVED_MEDIA,
    LOG_MESSAGE
};

struct SIPConnection {
    /*** network-settings ***/
    intptr_t socket_id;
    bool tcp = true;
    bool socket_active = false;

    /*** dns-settings ***/
    std::string fqdn;
    bool is_resolved = false;
    uint16_t dns_ttl = 0;
    std::string prio10_ip;
    std::string prio20_ip;
    std::string prio30_ip;

    /*** register-state ***/
    bool registered = false;
    std::string registered_uri {};
    std::string password {};
    std::string domain {};
    uint16_t reg_expire = 0;

    /*** call-state ***/
    bool call_active = false;
};

struct Event {
    EventType type;
    std::string_view log_message{};

    /*** SIP-payload related ***/
    std::string* raw_msg = nullptr;
    SIPMessage* raw_sip_message = nullptr;
    std::unique_ptr<SIPMessage> parsed_msg;
    mutable bool ownership_claimed = false;

    /*** Connection-related ***/
    SIPConnection* connection;

    //Network-related fields
    std::string dest_ip{};
    uint16_t dest_port = 0;
    uint16_t source_port = 0;
    bool use_tcp = true;
    intptr_t socket_handle = 0;
};


#endif //PROJECT_SIPX_EVENT_H